import type {
  AppStore,
  AssemblyStep,
  InventoryItem,
  Product,
  ProjectComponent,
  PurchaseItem,
  RobotProject,
  WiringConnection,
} from "@/types";
import { progressPercent } from "@/lib/utils";

const USER_ID = "00000000-0000-4000-8000-000000000001";
const PROJECT_ID = "11111111-1111-4111-8111-111111111111";
const NOW = "2026-08-01T10:00:00.000Z";

function inv(
  partial: Omit<InventoryItem, "total_value" | "user_id" | "created_at" | "updated_at"> & {
    id: string;
  }
): InventoryItem {
  const available = partial.quantity - partial.reserved_quantity;
  return {
    ...partial,
    user_id: USER_ID,
    total_value: partial.quantity * partial.unit_cost,
    created_at: NOW,
    updated_at: NOW,
    status:
      available <= 0 && partial.reserved_quantity > 0
        ? "RESERVED"
        : available <= 0
          ? "OUT_OF_STOCK"
          : available <= partial.minimum_stock
            ? "LOW_STOCK"
            : "AVAILABLE",
  };
}

function pc(
  partial: Partial<ProjectComponent> & {
    id: string;
    component_name: string;
    category: ProjectComponent["category"];
    quantity: number;
    purpose: string;
    where_used: string;
    required: boolean;
    suggested_specification: string;
    specification_confirmed: boolean;
    confidence: number;
    installation_location: string;
    inventory_status: ProjectComponent["inventory_status"];
    purchase_status: ProjectComponent["purchase_status"];
    available_quantity: number;
    missing_quantity: number;
    beginner_what_is_it: string;
    beginner_what_does_it_do: string;
    beginner_where_fits: string;
    beginner_what_else: string[];
  }
): ProjectComponent {
  return {
    component_id: null,
    inventory_item_id: null,
    image_url: null,
    unit_cost: 0,
    notes: "",
    reserved_quantity: 0,
    ...partial,
    user_id: USER_ID,
    project_id: PROJECT_ID,
    created_at: NOW,
    updated_at: NOW,
  };
}

export function createDemoStore(): AppStore {
  const project: RobotProject = {
    id: PROJECT_ID,
    user_id: USER_ID,
    name: "4-Wheel AI Inspection Robot",
    purpose: "Autonomous visual inspection of factory floors and warehouse aisles",
    description:
      "A beginner-friendly four-wheel mobile robot with ESP32 control, camera inspection, ultrasonic obstacle sensing, and differential drive.",
    target_load: "2 kg payload (camera + sensors)",
    dimensions: "400mm L x 300mm W x 250mm H (approx)",
    movement: "Differential drive, forward/reverse/turn in place",
    environment: "Indoor warehouse / factory floor, flat surface",
    power_preference: "12V rechargeable battery pack",
    status: "active",
    progress: "INVENTORY_CHECK",
    progress_percent: progressPercent("INVENTORY_CHECK"),
    cover_image_url: "/demo/inspection-robot.svg",
    is_demo: true,
    approved_at: null,
    created_at: NOW,
    updated_at: NOW,
  };

  const inventory: InventoryItem[] = [
    inv({
      id: "inv-esp32",
      item_name: "ESP32 Dev Board",
      category: "ELECTRONICS",
      brand: "Espressif",
      model: "ESP32-WROOM-32",
      sku: "ESP32-DEV-01",
      image_url: null,
      specification: "3.3V logic, WiFi + Bluetooth",
      unit: "pcs",
      quantity: 3,
      reserved_quantity: 0,
      minimum_stock: 1,
      unit_cost: 450,
      gst_percent: 18,
      supplier: "RoboParts India",
      purchase_date: "2026-06-10",
      storage_location: "Bin A1",
      compatible_projects: [PROJECT_ID],
      notes: "Good for controllers",
      status: "AVAILABLE",
    }),
    inv({
      id: "inv-motor",
      item_name: "DC Gear Motor",
      category: "MECHANICAL",
      brand: "Generic",
      model: "GA25-370",
      sku: "DCM-370-12V",
      image_url: null,
      specification: "12V, approx 100 RPM — Specification not confirmed for torque",
      unit: "pcs",
      quantity: 2,
      reserved_quantity: 0,
      minimum_stock: 2,
      unit_cost: 320,
      gst_percent: 18,
      supplier: "MotorMart",
      purchase_date: "2026-05-20",
      storage_location: "Bin B2",
      compatible_projects: [PROJECT_ID],
      notes: "Need 2 more for 4-wheel drive",
      status: "LOW_STOCK",
    }),
    inv({
      id: "inv-wheel",
      item_name: "Rubber Wheel 65mm",
      category: "MECHANICAL",
      brand: "Generic",
      model: "W65",
      sku: "WH-65",
      image_url: null,
      specification: "65mm diameter with hub",
      unit: "pcs",
      quantity: 4,
      reserved_quantity: 0,
      minimum_stock: 2,
      unit_cost: 80,
      gst_percent: 18,
      supplier: "MotorMart",
      purchase_date: "2026-05-20",
      storage_location: "Bin B3",
      compatible_projects: [PROJECT_ID],
      notes: "",
      status: "AVAILABLE",
    }),
    inv({
      id: "inv-driver",
      item_name: "Motor Driver L298N",
      category: "ELECTRONICS",
      brand: "ST",
      model: "L298N",
      sku: "DRV-L298N",
      image_url: null,
      specification: "Dual H-bridge — current rating REQUIRES VERIFICATION",
      unit: "pcs",
      quantity: 1,
      reserved_quantity: 0,
      minimum_stock: 1,
      unit_cost: 180,
      gst_percent: 18,
      supplier: "RoboParts India",
      purchase_date: "2026-06-01",
      storage_location: "Bin A2",
      compatible_projects: [PROJECT_ID],
      notes: "",
      status: "AVAILABLE",
    }),
    inv({
      id: "inv-battery",
      item_name: "12V Li-ion Battery Pack",
      category: "POWER",
      brand: "PowerCell",
      model: "PC-12V-5AH",
      sku: "BAT-12-5",
      image_url: null,
      specification: "12V nominal — capacity 5Ah claimed, verify before use",
      unit: "pcs",
      quantity: 1,
      reserved_quantity: 0,
      minimum_stock: 1,
      unit_cost: 1800,
      gst_percent: 18,
      supplier: "PowerHouse",
      purchase_date: "2026-07-01",
      storage_location: "Bin C1",
      compatible_projects: [PROJECT_ID],
      notes: "Handle with care",
      status: "AVAILABLE",
    }),
    inv({
      id: "inv-ultrasonic",
      item_name: "HC-SR04 Ultrasonic Sensor",
      category: "SENSORS",
      brand: "Generic",
      model: "HC-SR04",
      sku: "SNS-USR04",
      image_url: null,
      specification: "5V trig/echo distance sensor",
      unit: "pcs",
      quantity: 2,
      reserved_quantity: 0,
      minimum_stock: 1,
      unit_cost: 90,
      gst_percent: 18,
      supplier: "RoboParts India",
      purchase_date: "2026-06-15",
      storage_location: "Bin A3",
      compatible_projects: [PROJECT_ID],
      notes: "",
      status: "AVAILABLE",
    }),
    inv({
      id: "inv-screws",
      item_name: "M3 Screw Assortment",
      category: "FASTENERS",
      brand: "FastFix",
      model: "M3-KIT",
      sku: "FST-M3",
      image_url: null,
      specification: "M3 screws, nuts, washers assortment",
      unit: "kit",
      quantity: 5,
      reserved_quantity: 0,
      minimum_stock: 1,
      unit_cost: 120,
      gst_percent: 18,
      supplier: "Hardware Hub",
      purchase_date: "2026-04-01",
      storage_location: "Bin D1",
      compatible_projects: [],
      notes: "",
      status: "AVAILABLE",
    }),
    inv({
      id: "inv-wire",
      item_name: "22 AWG Hookup Wire",
      category: "WIRING",
      brand: "WirePro",
      model: "22AWG-MIX",
      sku: "WR-22",
      image_url: null,
      specification: "Mixed colors, 10m spool — ampacity REQUIRES VERIFICATION",
      unit: "spool",
      quantity: 2,
      reserved_quantity: 0,
      minimum_stock: 1,
      unit_cost: 150,
      gst_percent: 18,
      supplier: "Hardware Hub",
      purchase_date: "2026-04-10",
      storage_location: "Bin D2",
      compatible_projects: [],
      notes: "",
      status: "AVAILABLE",
    }),
  ];

  const projectComponents: ProjectComponent[] = [
    pc({
      id: "pc-motor",
      component_name: "DC Gear Motor",
      category: "MECHANICAL",
      quantity: 4,
      purpose: "Drive the four wheels",
      where_used: "Left/right wheel assemblies",
      required: true,
      suggested_specification: "12V gear motor — Specification not confirmed",
      specification_confirmed: false,
      confidence: 0.86,
      unit_cost: 320,
      installation_location: "Chassis motor mounts",
      inventory_item_id: "inv-motor",
      inventory_status: "PURCHASE_REQUIRED",
      purchase_status: "REQUIRED",
      available_quantity: 2,
      missing_quantity: 2,
      beginner_what_is_it: "A motor that moves the robot wheel.",
      beginner_what_does_it_do: "It gives movement to the robot.",
      beginner_where_fits: "Left/right wheel assembly.",
      beginner_what_else: ["Motor bracket", "Screws", "Motor driver", "Wires"],
    }),
    pc({
      id: "pc-wheel",
      component_name: "Rubber Wheel 65mm",
      category: "MECHANICAL",
      quantity: 4,
      purpose: "Ground contact and traction",
      where_used: "Motor shafts",
      required: true,
      suggested_specification: "65mm rubber wheel with hub",
      specification_confirmed: true,
      confidence: 0.9,
      unit_cost: 80,
      installation_location: "Motor output shafts",
      inventory_item_id: "inv-wheel",
      inventory_status: "AVAILABLE",
      purchase_status: "NOT_NEEDED",
      available_quantity: 4,
      missing_quantity: 0,
      beginner_what_is_it: "Round rubber parts that roll on the floor.",
      beginner_what_does_it_do: "They let the robot roll smoothly.",
      beginner_where_fits: "On each motor shaft.",
      beginner_what_else: ["Motors", "Shaft couplers or hubs", "Screws"],
    }),
    pc({
      id: "pc-driver",
      component_name: "Motor Driver L298N",
      category: "ELECTRONICS",
      quantity: 1,
      purpose: "Control motor direction and power",
      where_used: "Between ESP32 and motors",
      required: true,
      suggested_specification: "Dual H-bridge compatible with 12V motors — current REQUIRES VERIFICATION",
      specification_confirmed: false,
      confidence: 0.82,
      unit_cost: 180,
      installation_location: "Electronics deck",
      inventory_item_id: "inv-driver",
      inventory_status: "AVAILABLE",
      purchase_status: "NOT_NEEDED",
      available_quantity: 1,
      missing_quantity: 0,
      beginner_what_is_it: "A board that helps the small computer control strong motors.",
      beginner_what_does_it_do: "It turns motors on/off and changes direction safely.",
      beginner_where_fits: "Near the controller and battery.",
      beginner_what_else: ["ESP32", "Battery wires", "Motor wires"],
    }),
    pc({
      id: "pc-esp32",
      component_name: "ESP32 Dev Board",
      category: "ELECTRONICS",
      quantity: 1,
      purpose: "Main controller / brain of the robot",
      where_used: "Electronics deck",
      required: true,
      suggested_specification: "ESP32 with WiFi",
      specification_confirmed: true,
      confidence: 0.95,
      unit_cost: 450,
      installation_location: "Controller mount",
      inventory_item_id: "inv-esp32",
      inventory_status: "AVAILABLE",
      purchase_status: "NOT_NEEDED",
      available_quantity: 3,
      missing_quantity: 0,
      beginner_what_is_it: "A tiny computer that runs the robot program.",
      beginner_what_does_it_do: "It reads sensors and tells motors what to do.",
      beginner_where_fits: "On the electronics deck.",
      beginner_what_else: ["USB cable", "Motor driver", "Sensors", "Power regulation"],
    }),
    pc({
      id: "pc-camera",
      component_name: "ESP32-CAM / Inspection Camera",
      category: "SENSORS",
      quantity: 1,
      purpose: "Capture inspection images/video",
      where_used: "Front mast / pan-tilt mount",
      required: true,
      suggested_specification: "Specification not confirmed — camera module TBD",
      specification_confirmed: false,
      confidence: 0.7,
      unit_cost: 650,
      installation_location: "Front camera mount",
      inventory_status: "PURCHASE_REQUIRED",
      purchase_status: "REQUIRED",
      available_quantity: 0,
      missing_quantity: 1,
      beginner_what_is_it: "A small camera that looks at the surroundings.",
      beginner_what_does_it_do: "It takes pictures for inspection.",
      beginner_where_fits: "On the front of the robot.",
      beginner_what_else: ["Mount bracket", "Servo for pan/tilt", "Power cable"],
    }),
    pc({
      id: "pc-ultrasonic",
      component_name: "HC-SR04 Ultrasonic Sensor",
      category: "SENSORS",
      quantity: 2,
      purpose: "Obstacle distance sensing",
      where_used: "Front bumper left/right",
      required: true,
      suggested_specification: "HC-SR04 or equivalent 5V ultrasonic",
      specification_confirmed: true,
      confidence: 0.88,
      unit_cost: 90,
      installation_location: "Front bumper",
      inventory_item_id: "inv-ultrasonic",
      inventory_status: "AVAILABLE",
      purchase_status: "NOT_NEEDED",
      available_quantity: 2,
      missing_quantity: 0,
      beginner_what_is_it: "A sensor that measures distance using sound.",
      beginner_what_does_it_do: "It helps the robot avoid bumping into things.",
      beginner_where_fits: "Front of the robot.",
      beginner_what_else: ["Mount bracket", "Jumper wires"],
    }),
    pc({
      id: "pc-servo",
      component_name: "SG90 Micro Servo",
      category: "ELECTRONICS",
      quantity: 1,
      purpose: "Pan camera left/right",
      where_used: "Camera mount",
      required: false,
      suggested_specification: "5V micro servo — torque REQUIRES VERIFICATION",
      specification_confirmed: false,
      confidence: 0.75,
      unit_cost: 120,
      installation_location: "Camera pan mount",
      inventory_status: "PURCHASE_REQUIRED",
      purchase_status: "REQUIRED",
      available_quantity: 0,
      missing_quantity: 1,
      beginner_what_is_it: "A small motor that turns to an exact angle.",
      beginner_what_does_it_do: "It moves the camera left and right.",
      beginner_where_fits: "Under the camera.",
      beginner_what_else: ["Camera bracket", "Screws", "Signal wire"],
    }),
    pc({
      id: "pc-battery",
      component_name: "12V Battery Pack",
      category: "POWER",
      quantity: 1,
      purpose: "Power motors and electronics",
      where_used: "Battery bay",
      required: true,
      suggested_specification: "12V pack — capacity REQUIRES VERIFICATION",
      specification_confirmed: false,
      confidence: 0.8,
      unit_cost: 1800,
      installation_location: "Chassis battery bay",
      inventory_item_id: "inv-battery",
      inventory_status: "AVAILABLE",
      purchase_status: "NOT_NEEDED",
      available_quantity: 1,
      missing_quantity: 0,
      beginner_what_is_it: "The power source for the robot.",
      beginner_what_does_it_do: "It stores electricity so the robot can run.",
      beginner_where_fits: "In the battery bay under the deck.",
      beginner_what_else: ["Fuse", "Switch", "Battery holder", "Charger"],
    }),
    pc({
      id: "pc-fuse",
      component_name: "Inline Fuse Holder + Fuse",
      category: "POWER",
      quantity: 1,
      purpose: "Protect wiring from overcurrent",
      where_used: "Battery positive line",
      required: true,
      suggested_specification: "Fuse rating REQUIRES VERIFICATION based on motor current",
      specification_confirmed: false,
      confidence: 0.78,
      unit_cost: 60,
      installation_location: "Battery positive lead",
      inventory_status: "PURCHASE_REQUIRED",
      purchase_status: "REQUIRED",
      available_quantity: 0,
      missing_quantity: 1,
      beginner_what_is_it: "A safety part that breaks the circuit if current is too high.",
      beginner_what_does_it_do: "It helps protect wires and electronics.",
      beginner_where_fits: "On the battery positive wire.",
      beginner_what_else: ["Battery", "Switch", "Correct fuse rating"],
    }),
    pc({
      id: "pc-switch",
      component_name: "Power Switch",
      category: "POWER",
      quantity: 1,
      purpose: "Turn robot power on/off",
      where_used: "Side panel",
      required: true,
      suggested_specification: "DC switch rated for battery voltage/current — REQUIRES VERIFICATION",
      specification_confirmed: false,
      confidence: 0.85,
      unit_cost: 40,
      installation_location: "Chassis side panel",
      inventory_status: "PURCHASE_REQUIRED",
      purchase_status: "REQUIRED",
      available_quantity: 0,
      missing_quantity: 1,
      beginner_what_is_it: "A button or toggle that turns power on and off.",
      beginner_what_does_it_do: "It lets you safely power the robot.",
      beginner_where_fits: "On the side of the frame.",
      beginner_what_else: ["Fuse", "Battery wires"],
    }),
    pc({
      id: "pc-frame",
      component_name: "Chassis Frame",
      category: "MECHANICAL",
      quantity: 1,
      purpose: "Structural base for all parts",
      where_used: "Entire robot",
      required: true,
      suggested_specification: "Acrylic/aluminum chassis ~400x300mm — Specification not confirmed",
      specification_confirmed: false,
      confidence: 0.72,
      unit_cost: 900,
      installation_location: "Base structure",
      inventory_status: "PURCHASE_REQUIRED",
      purchase_status: "REQUIRED",
      available_quantity: 0,
      missing_quantity: 1,
      beginner_what_is_it: "The body/base that holds everything together.",
      beginner_what_does_it_do: "It gives the robot shape and strength.",
      beginner_where_fits: "It is the main structure.",
      beginner_what_else: ["Brackets", "Screws", "Motor mounts"],
    }),
    pc({
      id: "pc-brackets",
      component_name: "Motor Mount Brackets",
      category: "MECHANICAL",
      quantity: 4,
      purpose: "Hold motors to frame",
      where_used: "Motor mounting points",
      required: true,
      suggested_specification: "Metal brackets matching motor body",
      specification_confirmed: false,
      confidence: 0.8,
      unit_cost: 50,
      installation_location: "Chassis corners",
      inventory_status: "PURCHASE_REQUIRED",
      purchase_status: "REQUIRED",
      available_quantity: 0,
      missing_quantity: 4,
      beginner_what_is_it: "Metal pieces that hold the motors in place.",
      beginner_what_does_it_do: "They stop motors from moving or twisting.",
      beginner_where_fits: "Between motor and frame.",
      beginner_what_else: ["Motors", "Screws"],
    }),
    pc({
      id: "pc-bearings",
      component_name: "Support Bearings",
      category: "MECHANICAL",
      quantity: 4,
      purpose: "Reduce shaft friction if using extended shafts",
      where_used: "Optional shaft supports",
      required: false,
      suggested_specification: "Specification not confirmed",
      specification_confirmed: false,
      confidence: 0.55,
      unit_cost: 35,
      installation_location: "Shaft supports",
      inventory_status: "PURCHASE_REQUIRED",
      purchase_status: "REQUIRED",
      available_quantity: 0,
      missing_quantity: 4,
      beginner_what_is_it: "Small rings that help shafts spin smoothly.",
      beginner_what_does_it_do: "They reduce rubbing and wear.",
      beginner_where_fits: "Around rotating shafts if used.",
      beginner_what_else: ["Shafts", "Housing"],
    }),
    pc({
      id: "pc-wires",
      component_name: "Hookup Wires & Connectors",
      category: "WIRING",
      quantity: 1,
      purpose: "Electrical connections",
      where_used: "All electronics",
      required: true,
      suggested_specification: "22 AWG mixed + connectors — ampacity REQUIRES VERIFICATION",
      specification_confirmed: false,
      confidence: 0.84,
      unit_cost: 200,
      installation_location: "Cable harness routes",
      inventory_item_id: "inv-wire",
      inventory_status: "AVAILABLE",
      purchase_status: "NOT_NEEDED",
      available_quantity: 2,
      missing_quantity: 0,
      beginner_what_is_it: "Wires and plugs that connect electrical parts.",
      beginner_what_does_it_do: "They carry power and signals.",
      beginner_where_fits: "Between battery, controller, motors, and sensors.",
      beginner_what_else: ["Fuse", "Switch", "Cable ties"],
    }),
    pc({
      id: "pc-screws",
      component_name: "M3 Screws & Fasteners",
      category: "FASTENERS",
      quantity: 1,
      purpose: "Assemble mechanical parts",
      where_used: "Entire robot",
      required: true,
      suggested_specification: "M3 assortment",
      specification_confirmed: true,
      confidence: 0.9,
      unit_cost: 120,
      installation_location: "All mounting points",
      inventory_item_id: "inv-screws",
      inventory_status: "AVAILABLE",
      purchase_status: "NOT_NEEDED",
      available_quantity: 5,
      missing_quantity: 0,
      beginner_what_is_it: "Screws and nuts that hold parts together.",
      beginner_what_does_it_do: "They keep the robot assembled.",
      beginner_where_fits: "Everywhere parts join.",
      beginner_what_else: ["Screwdriver", "Hex keys"],
    }),
  ];

  const purchaseItems: PurchaseItem[] = [
    {
      id: "pur-motor",
      user_id: USER_ID,
      project_id: PROJECT_ID,
      purchase_order_id: null,
      item_name: "DC Gear Motor",
      required_qty: 4,
      available_qty: 2,
      purchase_qty: 2,
      recommended_product_id: "prod-motor-a",
      recommended_product_name: "GA25-370 12V Gear Motor",
      estimated_price: 320,
      estimated_total: 640,
      supplier: "MotorMart",
      priority: "CRITICAL",
      status: "REQUIRED",
      notes: "Purchase only missing quantity (2).",
      created_at: NOW,
      updated_at: NOW,
    },
    {
      id: "pur-camera",
      user_id: USER_ID,
      project_id: PROJECT_ID,
      purchase_order_id: null,
      item_name: "ESP32-CAM / Inspection Camera",
      required_qty: 1,
      available_qty: 0,
      purchase_qty: 1,
      recommended_product_id: "prod-cam",
      recommended_product_name: "ESP32-CAM Module",
      estimated_price: 650,
      estimated_total: 650,
      supplier: "RoboParts India",
      priority: "HIGH",
      status: "REQUIRED",
      notes: "",
      created_at: NOW,
      updated_at: NOW,
    },
    {
      id: "pur-servo",
      user_id: USER_ID,
      project_id: PROJECT_ID,
      purchase_order_id: null,
      item_name: "SG90 Micro Servo",
      required_qty: 1,
      available_qty: 0,
      purchase_qty: 1,
      recommended_product_id: null,
      recommended_product_name: "SG90 9g Servo",
      estimated_price: 120,
      estimated_total: 120,
      supplier: "RoboParts India",
      priority: "MEDIUM",
      status: "REQUIRED",
      notes: "",
      created_at: NOW,
      updated_at: NOW,
    },
    {
      id: "pur-fuse",
      user_id: USER_ID,
      project_id: PROJECT_ID,
      purchase_order_id: null,
      item_name: "Inline Fuse Holder + Fuse",
      required_qty: 1,
      available_qty: 0,
      purchase_qty: 1,
      recommended_product_id: null,
      recommended_product_name: "Inline fuse kit",
      estimated_price: 60,
      estimated_total: 60,
      supplier: "Hardware Hub",
      priority: "CRITICAL",
      status: "REQUIRED",
      notes: "Fuse rating requires verification.",
      created_at: NOW,
      updated_at: NOW,
    },
    {
      id: "pur-switch",
      user_id: USER_ID,
      project_id: PROJECT_ID,
      purchase_order_id: null,
      item_name: "Power Switch",
      required_qty: 1,
      available_qty: 0,
      purchase_qty: 1,
      recommended_product_id: null,
      recommended_product_name: "12V DC rocker switch",
      estimated_price: 40,
      estimated_total: 40,
      supplier: "Hardware Hub",
      priority: "HIGH",
      status: "REQUIRED",
      notes: "",
      created_at: NOW,
      updated_at: NOW,
    },
    {
      id: "pur-frame",
      user_id: USER_ID,
      project_id: PROJECT_ID,
      purchase_order_id: null,
      item_name: "Chassis Frame",
      required_qty: 1,
      available_qty: 0,
      purchase_qty: 1,
      recommended_product_id: null,
      recommended_product_name: "400x300mm robot chassis kit",
      estimated_price: 900,
      estimated_total: 900,
      supplier: "FrameWorks",
      priority: "CRITICAL",
      status: "REQUIRED",
      notes: "",
      created_at: NOW,
      updated_at: NOW,
    },
    {
      id: "pur-brackets",
      user_id: USER_ID,
      project_id: PROJECT_ID,
      purchase_order_id: null,
      item_name: "Motor Mount Brackets",
      required_qty: 4,
      available_qty: 0,
      purchase_qty: 4,
      recommended_product_id: null,
      recommended_product_name: "GA25 motor bracket",
      estimated_price: 50,
      estimated_total: 200,
      supplier: "MotorMart",
      priority: "HIGH",
      status: "REQUIRED",
      notes: "",
      created_at: NOW,
      updated_at: NOW,
    },
    {
      id: "pur-bearings",
      user_id: USER_ID,
      project_id: PROJECT_ID,
      purchase_order_id: null,
      item_name: "Support Bearings",
      required_qty: 4,
      available_qty: 0,
      purchase_qty: 4,
      recommended_product_id: null,
      recommended_product_name: "608 bearing (verify fit)",
      estimated_price: 35,
      estimated_total: 140,
      supplier: "Hardware Hub",
      priority: "LOW",
      status: "REQUIRED",
      notes: "Optional — confirm need after chassis design.",
      created_at: NOW,
      updated_at: NOW,
    },
  ];

  const products: Product[] = [
    {
      id: "prod-motor-a",
      user_id: USER_ID,
      product_name: "GA25-370 12V Gear Motor",
      brand: "Generic",
      model: "GA25-370",
      price: 320,
      mrp: 399,
      discount: 20,
      gst_percent: 18,
      shipping: 40,
      final_price: 360,
      quantity: 1,
      specification: "12V DC gear motor, approx 100 RPM",
      voltage: "12V",
      current: "Not available",
      rpm: "100 RPM (approx)",
      torque: "Not available",
      dimensions: "Not available",
      weight: "Not available",
      warranty: "Not available",
      product_url: "",
      image_url: null,
      source: "catalog",
      notes: "Compatible with existing inventory motors",
      created_at: NOW,
      updated_at: NOW,
    },
    {
      id: "prod-motor-b",
      user_id: USER_ID,
      product_name: "Premium 12V Metal Gear Motor",
      brand: "DriveMax",
      model: "DM-12-MG",
      price: 580,
      mrp: 699,
      discount: 17,
      gst_percent: 18,
      shipping: 50,
      final_price: 630,
      quantity: 1,
      specification: "12V metal gear, sealed body",
      voltage: "12V",
      current: "Not available",
      rpm: "120 RPM (approx)",
      torque: "Not available",
      dimensions: "Not available",
      weight: "Not available",
      warranty: "6 months",
      product_url: "",
      image_url: null,
      source: "catalog",
      notes: "Premium option",
      created_at: NOW,
      updated_at: NOW,
    },
    {
      id: "prod-cam",
      user_id: USER_ID,
      product_name: "ESP32-CAM Module",
      brand: "AI-Thinker",
      model: "ESP32-CAM",
      price: 650,
      mrp: 799,
      discount: 18,
      gst_percent: 18,
      shipping: 40,
      final_price: 690,
      quantity: 1,
      specification: "OV2640 camera with ESP32",
      voltage: "5V",
      current: "Not available",
      rpm: "Not available",
      torque: "Not available",
      dimensions: "Not available",
      weight: "Not available",
      warranty: "Not available",
      product_url: "",
      image_url: null,
      source: "catalog",
      notes: "",
      created_at: NOW,
      updated_at: NOW,
    },
  ];

  const assemblySteps: AssemblyStep[] = [
    {
      id: "asm-01",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      step_number: 1,
      title: "Build frame",
      instructions: "Assemble the chassis base plate and side rails. Keep the top deck removable for electronics access.",
      required_components: ["Chassis Frame", "M3 Screws & Fasteners"],
      quantities: { "Chassis Frame": 1, "M3 Screws & Fasteners": 1 },
      tools: ["Screwdriver", "Hex key set"],
      installation_location: "Work bench",
      reference_image_url: null,
      safety_warning: "Wear eye protection when drilling or cutting.",
      completed: false,
      completed_at: null,
      created_at: NOW,
    },
    {
      id: "asm-02",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      step_number: 2,
      title: "Install motor brackets",
      instructions: "Mount four motor brackets at the chassis corners. Align holes before tightening.",
      required_components: ["Motor Mount Brackets", "M3 Screws & Fasteners"],
      quantities: { "Motor Mount Brackets": 4 },
      tools: ["Screwdriver"],
      installation_location: "Chassis corners",
      reference_image_url: null,
      safety_warning: "Do not overtighten soft acrylic frames.",
      completed: false,
      completed_at: null,
      created_at: NOW,
    },
    {
      id: "asm-03",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      step_number: 3,
      title: "Install motors",
      instructions: "Secure each DC gear motor into its bracket. Route motor leads upward toward the electronics deck.",
      required_components: ["DC Gear Motor"],
      quantities: { "DC Gear Motor": 4 },
      tools: ["Screwdriver"],
      installation_location: "Motor mounts",
      reference_image_url: null,
      safety_warning: "Keep fingers clear of spinning shafts during later testing.",
      completed: false,
      completed_at: null,
      created_at: NOW,
    },
    {
      id: "asm-04",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      step_number: 4,
      title: "Install wheels",
      instructions: "Attach wheels to motor shafts and verify free rotation without rubbing the frame.",
      required_components: ["Rubber Wheel 65mm"],
      quantities: { "Rubber Wheel 65mm": 4 },
      tools: ["Allen key"],
      installation_location: "Motor shafts",
      reference_image_url: null,
      safety_warning: "Support chassis while fitting wheels.",
      completed: false,
      completed_at: null,
      created_at: NOW,
    },
    {
      id: "asm-05",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      step_number: 5,
      title: "Install battery holder",
      instructions: "Mount battery bay and secure straps/holder. Leave space for fuse and switch wiring.",
      required_components: ["12V Battery Pack"],
      quantities: { "12V Battery Pack": 1 },
      tools: ["Screwdriver"],
      installation_location: "Battery bay",
      reference_image_url: null,
      safety_warning: "Do not short battery terminals.",
      completed: false,
      completed_at: null,
      created_at: NOW,
    },
    {
      id: "asm-06",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      step_number: 6,
      title: "Install controller",
      instructions: "Mount ESP32 on standoffs. Keep USB port accessible for programming.",
      required_components: ["ESP32 Dev Board"],
      quantities: { "ESP32 Dev Board": 1 },
      tools: ["Screwdriver"],
      installation_location: "Electronics deck",
      reference_image_url: null,
      safety_warning: "Power off before wiring GPIO.",
      completed: false,
      completed_at: null,
      created_at: NOW,
    },
    {
      id: "asm-07",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      step_number: 7,
      title: "Install motor driver",
      instructions: "Mount L298N near motors. Connect motor outputs later during wiring stage.",
      required_components: ["Motor Driver L298N"],
      quantities: { "Motor Driver L298N": 1 },
      tools: ["Screwdriver"],
      installation_location: "Electronics deck",
      reference_image_url: null,
      safety_warning: "Verify voltage, current and polarity before connecting.",
      completed: false,
      completed_at: null,
      created_at: NOW,
    },
    {
      id: "asm-08",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      step_number: 8,
      title: "Install sensors",
      instructions: "Mount ultrasonic sensors on front bumper and camera/servo on front mast.",
      required_components: [
        "HC-SR04 Ultrasonic Sensor",
        "ESP32-CAM / Inspection Camera",
        "SG90 Micro Servo",
      ],
      quantities: {
        "HC-SR04 Ultrasonic Sensor": 2,
        "ESP32-CAM / Inspection Camera": 1,
        "SG90 Micro Servo": 1,
      },
      tools: ["Screwdriver", "Cable ties"],
      installation_location: "Front bumper / mast",
      reference_image_url: null,
      safety_warning: "Avoid stressing sensor pins.",
      completed: false,
      completed_at: null,
      created_at: NOW,
    },
    {
      id: "asm-09",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      step_number: 9,
      title: "Complete wiring",
      instructions: "Follow the wiring guide. Connect battery → fuse → switch → driver, then signal lines.",
      required_components: ["Hookup Wires & Connectors", "Inline Fuse Holder + Fuse", "Power Switch"],
      quantities: {
        "Hookup Wires & Connectors": 1,
        "Inline Fuse Holder + Fuse": 1,
        "Power Switch": 1,
      },
      tools: ["Wire stripper", "Multimeter"],
      installation_location: "Cable harness routes",
      reference_image_url: null,
      safety_warning: "Verify voltage, current and polarity before connecting.",
      completed: false,
      completed_at: null,
      created_at: NOW,
    },
    {
      id: "asm-10",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      step_number: 10,
      title: "Upload firmware",
      instructions: "Flash ESP32 with motor + sensor test firmware. Confirm serial monitor output.",
      required_components: ["ESP32 Dev Board"],
      quantities: { "ESP32 Dev Board": 1 },
      tools: ["Computer", "USB cable"],
      installation_location: "Workbench",
      reference_image_url: null,
      safety_warning: "Elevate wheels before first motor test.",
      completed: false,
      completed_at: null,
      created_at: NOW,
    },
    {
      id: "asm-11",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      step_number: 11,
      title: "Testing",
      instructions: "Test drive, obstacle detection, camera capture, and emergency stop via switch.",
      required_components: [],
      quantities: {},
      tools: ["Multimeter", "Tape measure"],
      installation_location: "Open floor test area",
      reference_image_url: null,
      safety_warning: "Supervise first powered runs. Keep clear of moving wheels.",
      completed: false,
      completed_at: null,
      created_at: NOW,
    },
  ];

  const wiring: WiringConnection[] = [
    {
      id: "w1",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      from_component: "Battery +",
      to_component: "Fuse",
      pin: "BAT+",
      wire: "Red 18–22 AWG (verify)",
      purpose: "Protected positive supply",
      voltage_note: "Verify battery voltage before connecting.",
      verified: false,
      warning: "Verify voltage, current and polarity before connecting.",
      created_at: NOW,
    },
    {
      id: "w2",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      from_component: "Fuse",
      to_component: "Switch",
      pin: "FUSE_OUT",
      wire: "Red",
      purpose: "Switched positive path",
      voltage_note: "Fuse rating REQUIRES VERIFICATION",
      verified: false,
      warning: "Verify voltage, current and polarity before connecting.",
      created_at: NOW,
    },
    {
      id: "w3",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      from_component: "Switch",
      to_component: "Motor Driver VIN+",
      pin: "SW_OUT",
      wire: "Red",
      purpose: "Power motor driver",
      voltage_note: "Driver input voltage must match battery — REQUIRES VERIFICATION",
      verified: false,
      warning: "Verify voltage, current and polarity before connecting.",
      created_at: NOW,
    },
    {
      id: "w4",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      from_component: "Battery -",
      to_component: "Motor Driver GND",
      pin: "BAT-",
      wire: "Black",
      purpose: "Common ground",
      voltage_note: "Common ground required",
      verified: false,
      warning: "Verify voltage, current and polarity before connecting.",
      created_at: NOW,
    },
    {
      id: "w5",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      from_component: "ESP32 GPIO",
      to_component: "Motor Driver Input",
      pin: "GPIO (TBD)",
      wire: "Signal jumper",
      purpose: "Motor direction/PWM control",
      voltage_note: "ESP32 is 3.3V logic — level shifting may be required",
      verified: false,
      warning: "Verify voltage, current and polarity before connecting.",
      created_at: NOW,
    },
    {
      id: "w6",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      from_component: "Motor Driver Output",
      to_component: "Motors",
      pin: "OUT1–OUT4",
      wire: "Motor leads",
      purpose: "Drive motors",
      voltage_note: "Motor current REQUIRES VERIFICATION",
      verified: false,
      warning: "Verify voltage, current and polarity before connecting.",
      created_at: NOW,
    },
    {
      id: "w7",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      from_component: "ESP32",
      to_component: "Ultrasonic Sensors",
      pin: "TRIG/ECHO",
      wire: "Dupont jumpers",
      purpose: "Distance sensing",
      voltage_note: "HC-SR04 often needs 5V — verify level compatibility",
      verified: false,
      warning: "Verify voltage, current and polarity before connecting.",
      created_at: NOW,
    },
    {
      id: "w8",
      project_id: PROJECT_ID,
      user_id: USER_ID,
      from_component: "ESP32",
      to_component: "Servo",
      pin: "PWM GPIO",
      wire: "Signal + 5V/GND",
      purpose: "Camera pan",
      voltage_note: "Servo supply current REQUIRES VERIFICATION",
      verified: false,
      warning: "Verify voltage, current and polarity before connecting.",
      created_at: NOW,
    },
  ];

  return {
    users: [
      {
        id: USER_ID,
        email: "builder@airobot.local",
        full_name: "Demo Builder",
        beginner_mode: true,
        theme: "dark",
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    robot_projects: [project],
    robot_images: [
      {
        id: "img-demo-1",
        project_id: PROJECT_ID,
        user_id: USER_ID,
        file_name: "inspection-robot.svg",
        file_path: "/demo/inspection-robot.svg",
        file_type: "image/svg+xml",
        file_size: 4096,
        image_kind: "concept",
        created_at: NOW,
      },
    ],
    robot_analysis: [
      {
        id: "an-demo-1",
        project_id: PROJECT_ID,
        user_id: USER_ID,
        provider: "mock",
        summary:
          "Likely a 4-wheel differential-drive inspection robot with onboard controller, camera, and front distance sensors. Exact motor torque, battery capacity, and fuse rating are not confirmed from the image.",
        markers: [
          { id: "m1", label: "01 Motor", x_percent: 18, y_percent: 68, component_name: "DC Gear Motor" },
          { id: "m2", label: "02 Battery", x_percent: 48, y_percent: 62, component_name: "12V Battery Pack" },
          { id: "m3", label: "03 Controller", x_percent: 52, y_percent: 38, component_name: "ESP32 Dev Board" },
          { id: "m4", label: "04 Camera", x_percent: 78, y_percent: 28, component_name: "ESP32-CAM / Inspection Camera" },
          { id: "m5", label: "05 Sensor", x_percent: 82, y_percent: 48, component_name: "HC-SR04 Ultrasonic Sensor" },
        ],
        warnings: [
          "Motor current and torque are unknown — REQUIRES VERIFICATION",
          "Battery capacity not confirmed from image",
          "Fuse rating cannot be determined without motor current data",
        ],
        raw_response: { mode: "demo" },
        created_at: NOW,
      },
    ],
    components: [],
    project_components: projectComponents,
    inventory,
    inventory_transactions: [
      {
        id: "tx-1",
        user_id: USER_ID,
        inventory_item_id: "inv-esp32",
        transaction_type: "RECEIVE",
        quantity: 3,
        previous_stock: 0,
        new_stock: 3,
        reason: "Initial stock",
        reference: "SEED",
        project_id: null,
        created_at: NOW,
      },
    ],
    products,
    product_scans: [
      {
        id: "scan-1",
        user_id: USER_ID,
        file_name: "amazon-motor-screenshot.png",
        file_path: "/demo/product-scan-placeholder.svg",
        file_type: "image/svg+xml",
        extracted_data: {
          product_name: "GA25-370 12V Gear Motor",
          brand: "Generic",
          price: 320,
          voltage: "12V",
          rpm: "100 RPM (approx)",
          current: "Not available",
        },
        provider: "mock",
        status: "extracted",
        error_message: null,
        created_at: NOW,
      },
    ],
    purchase_orders: [],
    purchase_items: purchaseItems,
    assembly_steps: assemblySteps,
    wiring_connections: wiring,
    documents: [
      {
        id: "doc-1",
        user_id: USER_ID,
        title: "Demo Project Overview",
        file_name: "demo-overview.txt",
        file_path: "/demo/demo-overview.txt",
        file_type: "text/plain",
        file_size: 256,
        entity_type: "project",
        entity_id: PROJECT_ID,
        metadata: { kind: "overview" },
        created_at: NOW,
      },
    ],
    ai_recommendations: [
      {
        id: "rec-1",
        user_id: USER_ID,
        project_id: PROJECT_ID,
        category: "procurement",
        title: "Purchase only 2 missing motors",
        body: "Inventory already has 2 compatible DC gear motors. Smart procurement recommends buying 2, not 4.",
        severity: "info",
        dismissed: false,
        created_at: NOW,
      },
      {
        id: "rec-2",
        user_id: USER_ID,
        project_id: PROJECT_ID,
        category: "safety",
        title: "Fuse rating unknown",
        body: "Do not finalize power wiring until motor stall current and fuse rating are verified.",
        severity: "warning",
        dismissed: false,
        created_at: NOW,
      },
      {
        id: "rec-3",
        user_id: USER_ID,
        project_id: PROJECT_ID,
        category: "engineering",
        title: "Driver current REQUIRES VERIFICATION",
        body: "L298N continuous current may be insufficient depending on motor load. Confirm before approving project.",
        severity: "critical",
        dismissed: false,
        created_at: NOW,
      },
    ],
    project_costs: [
      {
        id: "cost-1",
        project_id: PROJECT_ID,
        user_id: USER_ID,
        mechanical: 900 + 200 + 140 + 320 * 4 + 80 * 4,
        electronics: 450 + 180 + 120,
        sensors: 650 + 90 * 2,
        battery: 1800,
        wiring: 200 + 60 + 40,
        fasteners: 120,
        tools: 0,
        purchase: 640 + 650 + 120 + 60 + 40 + 900 + 200 + 140,
        shipping: 150,
        gst: 0,
        existing_inventory_value: 3 * 450 + 2 * 320 + 4 * 80 + 180 + 1800 + 2 * 90 + 5 * 120 + 2 * 150,
        new_purchase_cost: 640 + 650 + 120 + 60 + 40 + 900 + 200 + 140,
        total_robot_cost: (3 * 450 + 2 * 320 + 4 * 80 + 180 + 1800 + 2 * 90 + 5 * 120 + 2 * 150) + (640 + 650 + 120 + 60 + 40 + 900 + 200 + 140) + 150,
        updated_at: NOW,
      },
    ],
    project_notes: [
      {
        id: "note-1",
        project_id: PROJECT_ID,
        user_id: USER_ID,
        title: "Beginner tip",
        body: "Complete inventory check and buy only missing parts before assembly.",
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    engineering_checks: [
      {
        id: "eng-1",
        project_id: PROJECT_ID,
        user_id: USER_ID,
        overall_status: "REQUIRES_VERIFICATION",
        items: [
          {
            id: "ec1",
            check_name: "Motor voltage compatibility",
            status: "PASS",
            detail: "Motors and battery both target 12V nominal.",
          },
          {
            id: "ec2",
            check_name: "Battery capacity",
            status: "REQUIRES_VERIFICATION",
            detail: "Capacity claimed 5Ah but runtime under load is unknown.",
          },
          {
            id: "ec3",
            check_name: "Motor driver current rating",
            status: "REQUIRES_VERIFICATION",
            detail: "L298N continuous current vs motor stall current unknown.",
          },
          {
            id: "ec4",
            check_name: "Controller compatibility",
            status: "PASS",
            detail: "ESP32 can generate PWM/GPIO for driver inputs.",
          },
          {
            id: "ec5",
            check_name: "Sensor voltage",
            status: "REQUIRES_VERIFICATION",
            detail: "HC-SR04 often needs 5V while ESP32 is 3.3V logic.",
          },
          {
            id: "ec6",
            check_name: "Fuse requirement",
            status: "REQUIRES_VERIFICATION",
            detail: "Fuse amp rating cannot be confirmed without motor current data.",
          },
          {
            id: "ec7",
            check_name: "Missing components",
            status: "FAIL",
            detail: "Several required items are missing and must be purchased.",
          },
          {
            id: "ec8",
            check_name: "Unknown specifications",
            status: "REQUIRES_VERIFICATION",
            detail: "Torque, wire ampacity, and exact camera module are unconfirmed.",
          },
        ],
        created_at: NOW,
      },
    ],
    printer_profiles: [
      {
        id: "printer-bambu-default",
        user_id: USER_ID,
        name: "My Bambu Printer",
        brand: "Bambu Lab",
        model: "A1 / P1 / X1 (set yours)",
        bambu_handy_active: true,
        bambu_handy_notes: "Bambu Handy app download + active. Send print jobs via Handy or Studio.",
        lan_ip: "",
        access_code: "",
        serial: "",
        anydesk_id: "",
        ultraviewer_id: "",
        preferred_transfer: "ANYDESK",
        printer_pc_path: "C:\\Users\\Public\\RobotPrints",
        status: "READY",
        last_checked_at: null,
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    printable_parts: [
      {
        id: "pp-chassis",
        user_id: USER_ID,
        project_id: PROJECT_ID,
        part_name: "Chassis Base Plate",
        part_name_hi: "Chassis Base Plate / बेस प्लेट",
        purpose: "Main body plate for motors, board, and battery",
        purpose_hi: "Motors, board, battery के लिए मुख्य प्लेट",
        material: "PLA",
        color: "Black",
        quantity: 1,
        estimated_minutes: 180,
        file_name: "",
        file_path: "",
        file_type: "",
        file_size: 0,
        status: "NEEDED",
        notes: "Upload STL/3MF then send via AnyDesk → Bambu Handy.",
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: "pp-sensor-mount",
        user_id: USER_ID,
        project_id: PROJECT_ID,
        part_name: "Ultrasonic Sensor Mount",
        part_name_hi: "Ultrasonic Mount / सेंसर माउंट",
        purpose: "Holds HC-SR04 on the front",
        purpose_hi: "सामने HC-SR04 पकड़ता है",
        material: "PLA",
        color: "Any",
        quantity: 1,
        estimated_minutes: 45,
        file_name: "",
        file_path: "",
        file_type: "",
        file_size: 0,
        status: "NEEDED",
        notes: "Small first print — good Bambu Handy test.",
        created_at: NOW,
        updated_at: NOW,
      },
      {
        id: "pp-board-holder",
        user_id: USER_ID,
        project_id: PROJECT_ID,
        part_name: "ESP32 Holder",
        part_name_hi: "Board Holder / बोर्ड होल्डर",
        purpose: "Keeps controller fixed on chassis",
        purpose_hi: "Controller board फिक्स रखता है",
        material: "PLA",
        color: "Any",
        quantity: 1,
        estimated_minutes: 60,
        file_name: "",
        file_path: "",
        file_type: "",
        file_size: 0,
        status: "NEEDED",
        notes: "",
        created_at: NOW,
        updated_at: NOW,
      },
    ],
    print_jobs: [],
  };
}
